### ISSUE TITLE
【保留】[Infra] 複数IDE開発のためにspotless formatterを入れてみる

### ISSUE THREAD

**Issue by jflute** [dbflute/dbflute-intro#503]
Eclipse, IntelliJ, VSCodeと3つあって、フォーマッターの定義はだいぶ近づけてるけど若干の違いはある。

spotlessでgradleコマンドで(同じフォーマット定義で)フォーマットを実行できるようになるので、
github actionsとかでコミット時に自動でフォーマットが掛かるようにしてもいいかもしれない。
(そうだとしても早いフィードバックのためにIDE上でのフォーマットはそのままキープ)

// Spotless - keep your code spotless with Gradle
https://plugins.gradle.org/plugin/com.diffplug.spotless

基本、Java側の話。TypeScript側はPrettierがある。

ぶっちゃけspotlessを試してみたいというのもある。

```
plugins {
    // TODO hakiba riot v6移行後は npm コマンドはgradleから直接実行しないので削除して良い by 2022/06/01
    // #gradle8 mooworkが新しいGradleに対応していなくて落ちるので別のものを導入 by jflute (2024/11/02)
    //id 'com.moowork.node' version '1.3.1'               // ./gradlew npm_xxx
    id 'com.github.node-gradle.node' version "7.1.0"

    // #gradle8 upgrade to latest version to avoid redundant getter errors by jflute (2024/11/03)
    id 'com.github.hierynomus.license' version '0.16.1' // ./gradlew licenseMain

    // 複数IDE開発のためにspotless formatterを入れてみる by jflute (2024/11/02)
    // https://github.com/dbflute/dbflute-intro/issues/503
    // https://plugins.gradle.org/plugin/com.diffplug.spotless
    id 'com.diffplug.spotless' version "7.0.0.BETA4"
}

...

spotless {
  java {
    // _/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/
    // IDEで使っているフォーマット定義と同じもの。(Eclipseベース)
    // Gradleコマンドを実行するところ(実質プロジェクトルート)から相対パスで指定。
    // _/_/_/_/_/_/_/_/_/_/
    eclipse().configFile project.file("./etc/tools/eclipse/dbflute-eclipse-code-formatter.xml")

    // _/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/
    // 自動生成クラスをフォーマット対象から除外している。(主にDBFluteやLastaFlute)
    // 自動生成都合によるフォーマットはそのままの方が見やすいという想定で残すように。
    //
    // dbflute/**/allcommon/ は dbflute/allcommonも含まれる。
    // test側は同じパッケージでも自動生成じゃないこともあるので、mainとtestで区別している。
    // _/_/_/_/_/_/_/_/_/_/
    targetExclude(
        'src/main/java/**/dbflute/**/allcommon/'
      , 'src/main/java/**/dbflute/**/bsbhv/'
      , 'src/main/java/**/dbflute/**/bsentity/'
      , 'src/main/java/**/dbflute/**/cbean/bs/'
      , 'src/main/java/**/dbflute/**/cbean/cq/bs/'
      , 'src/main/java/**/dbflute/**/cbean/cq/ciq/'
      , 'src/main/java/**/dbflute/**/cbean/nss/'
      , 'src/main/java/**/mylasta/action/*HtmlPath.java'
      , 'src/main/java/**/mylasta/action/*Labels.java'
      , 'src/main/java/**/mylasta/action/*Messages.java'
      , 'src/main/java/**/mylasta/appcls/'
      , 'src/main/java/**/mylasta/direction/*Config.java'
      , 'src/main/java/**/mylasta/direction/*Env.java'
    )

    // _/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/
    // Eclipseのデフォルトに合わせている。VSCodeもデフォルトが同じなのでOK。
    // IntelliJは.ideaの設定で同じ形になるように調整している。
    // _/_/_/_/_/_/_/_/_/_/
    importOrder('java', 'javax', 'org', 'com')
    removeUnusedImports()
  }
}
```

**Comment by jflute** [comment]
Gradleが古いと言われた:
```
* What went wrong:
An exception occurred applying plugin request [id: 'com.diffplug.spotless', version: '7.0.0.BETA4']
> Failed to apply plugin [id 'com.diffplug.spotless']
   > Spotless requires Gradle 6.1.1 or newer, this was 4.10.2
```

**Comment by jflute** [comment]
試しに最低限の6.1.1にしてみたら...
```
distributionUrl=https\://services.gradle.org/distributions/gradle-6.1.1-all.zip
```

次のエラー、なんじゃこりゃ？
```
Starting a Gradle Daemon (subsequent builds will be faster)
java.lang.NoClassDefFoundError: Could not initialize class org.codehaus.groovy.vmplugin.v7.Java7
	at org.codehaus.groovy.vmplugin.VMPluginFactory.<clinit>(VMPluginFactory.java:43)
...
Caused by: java.lang.ExceptionInInitializerError: Exception org.codehaus.groovy.GroovyBugError [in thread "Daemon worker"]
	at org.codehaus.groovy.vmplugin.v7.Java7.<clinit>(Java7.java:45)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1160)
...
* What went wrong:
Could not initialize class org.codehaus.groovy.reflection.ReflectionCache
> Exception java.lang.NoClassDefFoundError: Could not initialize class org.codehaus.groovy.vmplugin.v7.Java7 [in thread "Daemon worker"]
```

**Comment by jflute** [comment]
最新と思われる8.10.2にすると...
```
distributionUrl=https\://services.gradle.org/distributions/gradle-8.10.2-all.zip
```

既存のgradleが動かないところがある:
```
* Where:
Script '/Users/jflute/works/dbflute/fess/workspace/dbflute-intro/gradle/gradlePlugin/commonJava.gradle' line: 16

* What went wrong:
A problem occurred evaluating script.
> Could not set unknown property 'classifier' for task ':sourcesJar' of type org.gradle.api.tasks.bundling.Jar.
```

commonJava.gradle:
```
task sourcesJar(type: Jar, dependsOn:classes) {
    classifier = 'sources'
    from sourceSets.main.allSource
}
```

**Comment by jflute** [comment]
6系の最新の6.9.1にすると...
```
distributionUrl=https\://services.gradle.org/distributions/gradle-6.9.1-all.zip
```

java21のファイル混ざってる？
```
* What went wrong:
Could not compile build file '/Users/jflute/works/dbflute/fess/workspace/dbflute-intro/build.gradle'.
> startup failed:
  General error during semantic analysis: Unsupported class file major version 65
  
  java.lang.IllegalArgumentException: Unsupported class file major version 65
```

**Comment by jflute** [comment]
次は7.3
```
distributionUrl=https\://services.gradle.org/distributions/gradle-7.3-all.zip
```

変わんない
```
* What went wrong:
Could not compile build file '/Users/jflute/works/dbflute/fess/workspace/dbflute-intro/build.gradle'.
> startup failed:
  General error during conversion: Unsupported class file major version 65
  
  java.lang.IllegalArgumentException: Unsupported class file major version 65
```

**Comment by jflute** [comment]
8.10.2にして、classifierの問題を解決するほうが良いかも知れない。
```
* Where:
Script '/Users/jflute/works/dbflute/fess/workspace/dbflute-intro/gradle/gradlePlugin/commonJava.gradle' line: 16

* What went wrong:
A problem occurred evaluating script.
> Could not set unknown property 'classifier' for task ':sourcesJar' of type org.gradle.api.tasks.bundling.Jar.
```

commonJava.gradle:
```
task sourcesJar(type: Jar, dependsOn:classes) {
    classifier = 'sources'
    from sourceSets.main.allSource
}
```

エラーメッセージでググったら...これかな？
https://stackoverflow.com/questions/75660848/could-not-set-unknown-property-classifier-for-task-idl-parsersourcejar-of
```
    AbstractArchiveTask API Cleanup

    The deprecated appendix, archiveName, archivePath, baseName, classifier, desintationDir, extension and version properties of the AbstractArchiveTask task type have been removed. Use the archiveAppendix, archiveFileName , archiveFile, archiveBaseName, archiveClassifier, destinationDirectory, archiveExtension and archiveVersion properties instead.
```

archiveClassifierを使えということだろうか？
ということで使ってみたら先には進んだっぽいが別にエラー:
```
* Where:
Script '/Users/jflute/works/dbflute/fess/workspace/dbflute-intro/gradle/gradlePlugin/eclipse.gradle' line: 36

* What went wrong:
A problem occurred evaluating script.
> Could not find method leftShift() for arguments [eclipse_9rl0qqh2p5wrd8dbfou0qklpj$_run_closure3@11744625] on task ':eclipseJdt' of type org.gradle.plugins.ide.eclipse.GenerateEclipseJdt.
```

この辺の話かな？leftShift()って << のことか？
eclipse.gradle:
```
tasks.eclipseJdt {
    assert "org.eclipse.jdt.core.prefs" == outputFile.name
    ext.originalOutputFile = outputFile
    outputFile = (outputFile.absolutePath + ".tmp") as File
}
tasks.eclipseJdt << {
    assert "org.eclipse.jdt.core.prefs.tmp" == outputFile.name
    assert "org.eclipse.jdt.core.prefs" == ext.originalOutputFile.name
    List lines = outputFile.readLines(encoding)
    Collections.sort(lines)
    ext.originalOutputFile.withWriter(encoding) { writer ->
        lines.each { line ->
            writer << line
            writer << "\n"
        }
    }
    assert outputFile.delete()
}
```

これか？
https://teratail.com/questions/187565
```
ベストアンサー

<< による記法は Gradle 3.2 で非推奨となり、Gradle 5.0 で廃止になったようです。
...
上述のように Task.doLast() を代わりに使用するのが適切かと思います。
```

最近よく見かけるdoLast()を使うのかー。
doLast()の使い方合ってるかわからないけどとりあえずdoLast()にしてみたら...
```
tasks.eclipseJdt {
    doLast() {
        assert "org.eclipse.jdt.core.prefs.tmp" == outputFile.name
        assert "org.eclipse.jdt.core.prefs" == ext.originalOutputFile.name
        List lines = outputFile.readLines(encoding)
        Collections.sort(lines)
        ext.originalOutputFile.withWriter(encoding) { writer ->
            lines.each { line ->
                writer << line
                writer << "\n"
            }
        }
        assert outputFile.delete()
    }
    assert "org.eclipse.jdt.core.prefs" == outputFile.name
    ext.originalOutputFile = outputFile
    outputFile = (outputFile.absolutePath + ".tmp") as File
}
```

こんどはcommon.gradleの方でエラー:
```
* Where:
Script '/Users/jflute/works/dbflute/fess/workspace/dbflute-intro/gradle/gradlePlugin/common.gradle' line: 1

* What went wrong:
A problem occurred evaluating script.
> Cannot add task 'wrapper' as a task with that name already exists.
```

common.gradle:
```
task wrapper(type: Wrapper) {
    gradleVersion = versions.gradle
}
```

こんどはこれか？
// 「Cannot add task 'wrapper' as a task with that name already exists.」が出た
https://qiita.com/Yu-s/items/13a6a8db8dc191bb3b42
```
使用しているGradleのバージョンが5.X(5系)の場合、以下の「task wrapper」の記述は使えない。
...
「task wrapper」 → 「wapper」に記述を修正したら正常に動いた。
```
これもそう:
// Cannot add task 'wrapper' as a task with that name already exists
https://stackoverflow.com/questions/53709282/cannot-add-task-wrapper-as-a-task-with-that-name-already-exists
```
wrapper {
    gradleVersion = '4.4'
    distributionUrl = distributionUrl.replace("bin", "all")
}
```

やってみたらまた別のエラー:
```
* Where:
Build file '/Users/jflute/works/dbflute/fess/workspace/dbflute-intro/build.gradle' line: 96

* What went wrong:
A problem occurred evaluating root project 'dbflute-intro'.
> Could not find method compile() for arguments [org.dbflute:dbflute-runtime:1.2.6] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
```

これは、compileじゃなくてimplementationを使うやつじゃないだろうか？
https://stackoverflow.com/questions/23796404/could-not-find-method-compile-for-arguments-gradle

そろそろコメントを分けよう

**Comment by jflute** [comment]
↑の続き (Gradleを8系にしてあれこれ)

dependency周りのcompileなどをimplementationなどに変更して...
```
war {
    def embeddedArtifactList = ['javax.servlet-api', 'jetty-boot', 'jetty-all']
    configurations.implementation.collect { file ->
        if (embeddedArtifactList.any { file.getName().startsWith(it) }) {
...
```

configurations.implementationがダメだと言われた:
```
* Where:
Build file '/Users/jflute/works/dbflute/fess/workspace/dbflute-intro/build.gradle' line: 126

* What went wrong:
A problem occurred evaluating root project 'dbflute-intro'.
> Resolving dependency configuration 'implementation' is not allowed as it is defined as 'canBeResolved=false'.
  Instead, a resolvable ('canBeResolved=true') dependency configuration that extends 'implementation' should be resolved.
```

代わりにruntimeClasspathを使う？
https://stackoverflow.com/questions/47910578/not-able-to-copy-configurations-dependencies-after-upgrading-gradle-plugin-for-a
```
instead of using configurations.implementation, the best option is to use configurations.runtimeClasspath.

You can also think about: compileClasspath default
```

すると次のエラー、classesDirってプロパティないよ:
```
* Where:
Build file '/Users/jflute/works/dbflute/fess/workspace/dbflute-intro/build.gradle' line: 137

* What went wrong:
A problem occurred evaluating root project 'dbflute-intro'.
> Could not get unknown property 'classesDir' for main classes of type org.gradle.api.internal.tasks.DefaultSourceSetOutput.
```

classesDirからclassesDirsに変わった？
https://stackoverflow.com/questions/54707148/gradle-could-not-get-unknown-property-classesdir-for-main-classes
```
n Gradle 5.x, this property has been renamed to classesDirs from classesDir.

You can find more information [here](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.SourceSetOutput.html#org.gradle.api.tasks.SourceSetOutput:classesDirs)
```

次、extensionがないぞぅ:
```
* Where:
Build file '/Users/jflute/works/dbflute/fess/workspace/dbflute-intro/build.gradle' line: 144

* What went wrong:
A problem occurred evaluating root project 'dbflute-intro'.
> Could not set unknown property 'extension' for task ':war' of type org.gradle.api.tasks.bundling.War.
```

変わり過ぎじゃない？苦笑
これちょっとググってもすぐには出てこないぞぅ。

extensionやめたらspotless動いたけど、これでいいのか？拡張子がwarになっちゃわない？
```
    // already unneeded by DEFAULT_EXTENSION?
    //extension = 'jar'
```

gradleのソースコードを読んで、こうすればいけるかな？
```
archiveExtension.set('jar')
```

一応、spotless自体は動いた。Introのデプロイができるかどうかを試さないと。

**Comment by jflute** [comment]
./gradlew releaseすると、Javaのバージョンで怒られてしまった。
```
* What went wrong:
A problem occurred configuring root project 'dbflute-intro'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve com.diffplug.spotless:spotless-plugin-gradle:7.0.0.BETA4.
     Required by:
         root project : > com.diffplug.spotless:com.diffplug.spotless.gradle.plugin:7.0.0.BETA4
      > Dependency requires at least JVM runtime version 11. This build uses a Java 8 JVM.
```

これは悩ましい...
実行がJava11だけどJava8コンパイルのjarを作るってできないかな？

**Comment by jflute** [comment]
試しにJava11でreleaseビルドやってみたら...
```
export JAVA_HOME=$(/usr/libexec/java_home -v 11)
./gradlew release
```

node？
```
* What went wrong:
Execution failed for task ':nodeSetup'.
> Could not find method layout() for arguments [pattern, com.moowork.gradle.node.task.SetupTask$_addRepository_closure5$_closure7@6f30df16] on object of type org.gradle.api.internal.artifacts.repositories.DefaultIvyArtifactRepository.
```

frontend.gradleだろうか？でも、layout()というメソッドは読んでいない。

gradleプロセスの中でnpmコマンドは叩かれるとのこと。
でも、どこでどう呼ばれる？
```
// gradle 経由で npm コマンドが実行されるのは主にjarファイルを固める場合のみ
// jarファイルを固める前には、念の為フロントの成果物を消して作り直す
['npm_run_build': ['cleanDist', 'copyStaticResource']].each {
```

↓これっぽい？
// Could not find method layout() on upgrading to gradle 7.2
https://discuss.gradle.org/t/could-not-find-method-layout-on-upgrading-to-gradle-7-2/41194
```
You appear to be trying to use the [com.moowork.node 22](https://plugins.gradle.org/plugin/com.moowork.node) Gradle Node plugin, which is no longer maintained
by the original author and does not support recent versions of Gradle.

If you need to run Node tasks in your Gradle build,
migrate to a plugin that is still maintained,
like the [com.github.node-gradle.node 214](https://plugins.gradle.org/plugin/com.github.node-gradle.node)
Gradle Node plugin.
```

まさしく今、moowork.nodeを使っている。
```
id 'com.moowork.node' version '1.3.1'
```

↓こっちにしましょうということか？
// Gradle plugin for executing node scripts.
https://plugins.gradle.org/plugin/com.github.node-gradle.node

ということで単純に差し替えてみたけどこれでいいのか？
```
// #gradle8 mooworkが新しいGradleに対応していなくて落ちるので別のものを導入 by jflute (2024/11/02)
//id 'com.moowork.node' version '1.3.1'               // ./gradlew npm_xxx
id 'com.github.node-gradle.node' version "7.1.0"
```

**Comment by jflute** [comment]
↑の続き: 別のnodeのgradleプラグインを入れてみた。
nodeのインストールっぽいことはしているが...
```
> Task :npmInstall

added 116 packages, removed 266 packages, changed 112 packages, and audited 719 packages in 10s

34 packages are looking for funding
  run `npm fund` for details

39 vulnerabilities (2 low, 6 moderate, 14 high, 17 critical)

To address issues that do not require attention, run:
  npm audit fix
```

Javaの方で落ちた。
```
> Task :compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Error while evaluating property 'javaCompiler' of task ':compileJava'.
   > Failed to calculate the value of task ':compileJava' property 'javaCompiler'.
      > The configured executable does not exist (/Users/jflute/.gradle/daemon/8.10.2/javac)
```

// Failed to calculate the value of task ':compileJava' property 'javaCompiler'
https://stackoverflow.com/questions/72020442/failed-to-calculate-the-value-of-task-compilejava-property-javacompiler

他の記事を見ても、なんかJavaのバージョンが古いとダメ的な？
でも、17, 21にJAVA_HOMEを変えてみても変わらず。

この部分が全然なんじゃそりゃ？
```
The configured executable does not exist (/Users/jflute/.gradle/daemon/8.10.2/javac)
```

**Comment by jflute** [comment]
試行錯誤で、options.fork = true を false にしてみたら...
```
compileJava {
    options.compilerArgs << '-parameters'
    options.fork = false
    options.forkOptions.executable = 'javac'
}
```

エラーが変わった:
```
FAILURE: Build failed with an exception.

* What went wrong:
Some problems were found with the configuration of task ':licenseMain' (type 'License').
  - In plugin 'com.github.hierynomus.license' type 'nl.javadude.gradle.plugins.license.License' property 'check' has redundant getters: 'getCheck()' and 'isCheck()'.
    
    Reason: Boolean property 'check' has both an `is` and a `get` getter.
    
    Possible solutions:
      1. Remove one of the getters.
      2. Annotate one of the getters with @Internal.
    
    For more information, please refer to https://docs.gradle.org/8.10.2/userguide/validation_problems.html#redundant_getters in the Gradle documentation.
  - In plugin 'com.github.hierynomus.license' type 'nl.javadude.gradle.plugins.license.License' property 'dryRun' has redundant getters: 'getDryRun()' and 'isDryRun()'.
    
    Reason: Boolean property 'dryRun' has both an `is` and a `get` getter.
    
    Possible solutions:
      1. Remove one of the getters.
      2. Annotate one of the getters with @Internal.
    
    For more information, please refer to https://docs.gradle.org/8.10.2/userguide/validation_problems.html#redundant_getters in the Gradle documentation.
  - In plugin 'com.github.hierynomus.license' type 'nl.javadude.gradle.plugins.license.License' property 'ignoreFailures' has redundant getters: 'getIgnoreFailures()' and 'isIgnoreFailures()'.
    
    Reason: Boolean property 'ignoreFailures' has both an `is` and a `get` getter.
    
    Possible solutions:
      1. Remove one of the getters.
      2. Annotate one of the getters with @Internal.
    
    For more information, please refer to https://docs.gradle.org/8.10.2/userguide/validation_problems.html#redundant_getters in the Gradle documentation.
  - In plugin 'com.github.hierynomus.license' type 'nl.javadude.gradle.plugins.license.License' property 'skipExistingHeaders' has redundant getters: 'getSkipExistingHeaders()' and 'isSkipExistingHeaders()'.
    
    Reason: Boolean property 'skipExistingHeaders' has both an `is` and a `get` getter.
    
    Possible solutions:
      1. Remove one of the getters.
      2. Annotate one of the getters with @Internal.
    
    For more information, please refer to https://docs.gradle.org/8.10.2/userguide/validation_problems.html#redundant_getters in the Gradle documentation.
  - In plugin 'com.github.hierynomus.license' type 'nl.javadude.gradle.plugins.license.License' property 'strictCheck' has redundant getters: 'getStrictCheck()' and 'isStrictCheck()'.
    
    Reason: Boolean property 'strictCheck' has both an `is` and a `get` getter.
    
    Possible solutions:
      1. Remove one of the getters.
      2. Annotate one of the getters with @Internal.
    
    For more information, please refer to https://docs.gradle.org/8.10.2/userguide/validation_problems.html#redundant_getters in the Gradle documentation.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.
```

com.github.hierynomus.licenseがへんてこりんって感じのエラーなので、
com.github.hierynomus.licenseのバージョンを最新版にしてみたらエラーが変わった。

```
Execution failed for task ':spotlessJavaCheck'.
> The following files had format violations:
      src/main/java/org/dbflute/intro/app/logic/dfprop/DfpropReadLogic.java
          @@ -183,7 +183,8 @@
           ········documentMap.setCheckColumnDefOrderDiff(convertSettingToBoolean(readMap.get("isCheckColumnDefOrderDiff")));
           ········documentMap.setCheckDbCommentDiff(convertSettingToBoolean(readMap.get("isCheckDbCommentDiff")));
           ········documentMap.setCheckProcedureDiff(convertSettingToBoolean(readMap.get("isCheckProcedureDiff")));
          -········documentMap.setNeighborhoodSchemaHtmlMap(new·NeighborhoodSchemaHtmlMap(convertSettingToMap(readMap.get("neighborhoodSchemaHtmlMap"))));
          +········documentMap
          +················.setNeighborhoodSchemaHtmlMap(new·NeighborhoodSchemaHtmlMap(convertSettingToMap(readMap.get("neighborhoodSchemaHtmlMap"))));
           ········documentMap.setSchemaDiagramMap(new·SchemaDiagramMap(convertSettingToMap(readMap.get("schemaDiagramMap"))));
           ········return·documentMap;
           ····}
      src/main/java/org/dbflute/intro/app/model/client/ClientModel.java
...

      ... (8 more lines that didn't fit)
  Violations also present in 42 other files.
  Run './gradlew :spotlessApply' to fix these violations.
```

これは、spotlessのcheckが動いてフォーマットダメぴょんエラーなので、
かなり良いところまで動いたってことか？

一方で、spotlessApplyしてからじゃないとbuildできないよってことか。

**Comment by jflute** [comment]
spotlessApplyでformatしてからまたbuildしてみたら...

logback.xmlがなんか言われた？
```
* What went wrong:
Execution failed for task ':jar'.
> Entry logback.xml is a duplicate but no duplicate handling strategy has been set. Please refer to https://docs.gradle.org/8.10.2/dsl/org.gradle.api.tasks.Copy.html#org.gradle.api.tasks.Copy:duplicatesStrategy for details.
```

ちょっと状況違うけど、参考に↓
// Gradleaのリソースコピーエラーを解消する
https://zenn.dev/t_zomu/articles/4e97ce0059139a

logback.xmlが何かしらの原因で複数になってしまっているのかな？

// Gradle "Entry .classpath is a duplicate but no duplicate handling strategy has been set
https://stackoverflow.com/questions/67265308/gradle-entry-classpath-is-a-duplicate-but-no-duplicate-handling-
strategy-has-b
```
I was having the same issues while executing some tests in IntelliJ. What helped me was just run a simple gradle clean.
```

単純に gradlew clean してから build したらうまくいった！

ようやっと build が successful になったー！

今度は、release までやってみる。

**Comment by jflute** [comment]
releaseもsuccessfulにはなったけど...jarファイルが実行できない。
```
$ java -jar build/libs/dbflute-intro.jar
build/libs/dbflute-intro.jarにメイン・マニフェスト属性がありません
```

jarをzipにして解凍してみると、確かにMANIFEST.MFが全然何も入ってない。
```
Manifest-Version: 1.0
```

本来だったら、たぶんもっと入ってないといけないはず:
```
manifest {
    attributes 'Implementation-Title': project.name
    attributes 'Implementation-Version': project.version
    attributes 'SCM-Branch': scmBranch
    attributes 'SCM-Revision': scmRevision
    attributes 'Build-Timestamp': new java.text.SimpleDateFormat('yyyy/MM/dd HH:mm:ss.SSS').format(new Date())
    attributes 'Jenkins-Build-Number': System.getenv()['BUILD_NUMBER'] ?: ''
    attributes 'Main-Class': mainClassName
}
```

既存のdbflute-intro.jarを確認しようとzipに変更して解凍しようとしたけど、
Macのアーカイブユーティリティにエラー79: ...フォーマットが不適切ですと怒られてしまう。
これはこれでなんで？

// MacでZIPファイルを展開できない時の対処方法
https://qiita.com/H-Iida/items/c478536eaf49cf980488

terminalのunzipで解凍したら解凍できた。
やはり既存のjarにはしっかり情報が入っている。
```
Manifest-Version: 1.0
Implementation-Title: dbflute-intro
Implementation-Version: 0.6.0
SCM-Branch: master
SCM-Revision: aa74dfb516c6b43693c7722bb3ec46a44b174ec4
Build-Timestamp: 2022/07/13 20:08:05.428
Jenkins-Build-Number: 
Main-Class: org.dbflute.intro.IntroBoot
```

また、直下に main.js とか manifest.json とか WEB-INF とかのfrontendファイルやweb周りが入ってなくて、
全然不完全なjarファイルになっている。

warタスクが全然まともに動いてないっぽい？

**Comment by jflute** [comment]
久しぶりの整理。コメント↑の試行錯誤は、Java11で試してみた時の。

Java8環境だと、そもそもspotlessが動かないので論外。
```
* What went wrong:
A problem occurred configuring root project 'dbflute-intro'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve com.diffplug.spotless:spotless-plugin-gradle:7.0.0.BETA4.
     Required by:
         root project : > com.diffplug.spotless:com.diffplug.spotless.gradle.plugin:7.0.0.BETA4
      > Dependency requires at least JVM runtime version 11. This build uses a Java 8 JVM.
```

まあ、続けててもつらいから、IntroがJava11以降になったときに再会するみたいな感じにしようかな。
